FROM node:14.18.1-alpine3.12 as builder

COPY ./package.json yarn.lock ./

RUN yarn

COPY apps/WorkerMessage ./apps/WorkerMessage

COPY libs ./libs

COPY plugins ./plugins

COPY tsconfig.* ./

COPY nest-cli.json ./

RUN yarn build WorkerMessage

FROM node:14.18.1-alpine3.12 as app

WORKDIR /usr/src/app

COPY --from=builder dist  ./dist
COPY --from=builder node_modules ./node_modules
COPY --from=builder package.json ./

CMD ["sh", "-c", "node dist/apps/WorkerMessage/main.js"]
